change exit error

diff --git a/screen b/screen
--- a/screen
+++ b/screen
@@ -1,5 +1,9 @@
 #!/bin/bash
 #Remi ROBERT
+#exit code
+#0 : success
+#1 : no argument
+#2 : bad argument
 
 if [ $# != 1 ] || [ $1 == "-h" ] || [ $1 == "--help" ]
 then
@@ -7,14 +11,19 @@ then
     echo "-o --on                  put on the screen"
     echo "-f --of                  put off the screen"
     echo "-h --help                display this help and exit"
-    exit 1
+    if [ $# != 1 ]
+    then
+	exit 1
+    else
+	exit 0
+    fi
 fi
 
 if [ $1 != "-o" ] && [ $1 != "--on" ] &&
     [ $1 != "-f" ] && [ $1 != "--off" ]
 then
     echo "${1} command not found. Display the help : -h or --help"
-    exit 1
+    exit 2
 fi
 
 if [ $1 == "-o" ] || [ $1 == "--on" ]
